name: API
favicon: null
layout_spectrum: 0.37948943697847426
typography_spectrum: 0.18434734642505646
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4373949281871319
  lightness: 0.38097505434416234
  saturation: 0.9185549132525921
  rhythmicContrast: 0.7156773575115949
purpose: []
